language: scala
scala:
   - 2.11.7   
env:
  - DATABASE_URL_TEST='jdbc:postgresql://localhost:5432/kontrolletti_test?characterEncoding=UTF-8'
jdk:
  - oraclejdk8

addons:
  postgresql: "9.4"

before_script:
  - psql -f 'conf/db-setup/initialize-test-db.sql' -U postgres 

script:
  - sbt clean coverage test
  - sbt coverageReport

after_success:
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash)
