language: scala
scala:
   - 2.11.7   

jdk:
  - oraclejdk8

addon:
  postgresql: "9.4"

before_script:
  - psql -f 'conf/db-setup/initialize-test-db.sql' -U postgres 

script:
  - sbt clean coverage test -Dconfig.resource=application.travis.conf
  - sbt coverageReport

after_success:
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash)
