language: scala
scala:
   - 2.11.1   
jdk:
  - oraclejdk8
script:
  - sbt clean coverage test
  - sbt coverageReport
after_success:
  - sbt codacyCoverage
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash)
