language: scala
scala:
   - 2.11.7   

jdk:
  - oraclejdk8

addon:
  postgresql: "9.4"

before_script:
  - psql -U postgres -f conf/db-setup/initialize-test-db.sql

script:
  - sbt clean coverage test -Dconfig.file=conf/application.test.conf
  - sbt coverageReport

after_success:
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash)
