language: scala
scala:
   - 2.11.7   

jdk:
  - oraclejdk8

addon:
  postgresql: "9.4"

env:
- DATABASE_URL="jdbc:postgresql://localhost:5432/kontrolletti_test?characterEncoding=UTF-8"

before_script:
  - psql -f 'conf/db-setup/initialize-test-db.sql' -U postgres 

script:
  - sbt clean coverage test
  - sbt coverageReport

after_success:
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash)
